name: Build Image CI

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
      backend-uri:
        description: 'Backend URI'
        required: true
        default: 'https://kathakali.comp.nus.edu.sg/api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup environment variables
        run: |
          echo "VITE_BACKEND_URI=${{ github.event.inputs.backend-uri }}" >> $GITHUB_ENV
          echo "VITE_EMAIL_API_KEY=${{ secrets.VITE_EMAIL_API_KEY }}" >> $GITHUB_ENV
      - run: npm ci
      - name: Build the app
        run: npm run build
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u culture4web --password-stdin
      - name: Build the Docker image
        run: docker build -t culture4web/culture-web-fe:${{ github.event.inputs.image-tag }} .
      - name: Push the Docker image
        run: docker push culture4web/culture-web-fe:${{ github.event.inputs.image-tag }}
